export default [
  {
    title: 'Your Love Keeps Lifting Me Higher',
    chords: ['D', 'G', 'G6'],
    lines: [['D', 'G', 'G6', 'D']],
    links: [],
  },
  {
    title: 'Skinny Love',
    chords: ['Am', 'C', 'G', 'F'],
    lines: [
      ['Intro + Verse 1'],
      ['Am', 'C', 'G', 'G', '(3x)'],
      ['G', 'G', 'Am', 'Am'],
      ['Break '],
      ['Am', 'Am', 'Am', 'G'],
      ['Verse 2'],
      ['...'],
      ['Chorus'],
      ['C', 'C', 'G', 'F'],
      ['Break after chorus'],
      ['F', 'F', 'F', 'F'],
      ['Verse 3'],
      ['...'],
      ['Break'],
      ['Am', 'Am', 'Am', 'Am'],
      ['Chorus'],
      ['C', 'C', 'G', 'F', '(4x)'],
      ['Break after chorus'],
      ['F', 'F', 'F', 'F'],
      ['Outro'],
      ['C', 'C', 'G', 'F', '(2x)'],
      ['F', 'F', 'F', 'F'],
      ['Am', 'C', 'G', 'G', '(2x)'],
    ],
    links: [],
  },
  {
    title: 'Twist In My Sobriety',
    chords: ['Em', 'Am7', 'B'],
    lines: [
      ['Verse'],
      ['Em', 'Am7', 'B', 'Em'],
      ['Em', 'Am7', 'B', 'Em'],
      ['B', 'Em'],
      ['Chorus'],
      ['B', 'Em'],
      ['B', 'Em'],
      ['Am7', 'Em', 'B', 'Em'],
      ['B', 'Em', 'B', '(Em)'],
      ['Break'],
      ['to do...', 'to do...', 'to do...'],
    ],
    links: [
      'https://tabs.ultimate-guitar.com/tab/tanita-tikaram/twist-in-my-sobriety-chords-1394609',
    ],
  },
  {
    title: "That's Alright Mama",
    chords: ['C', 'C7', 'F', 'G7'],
    lines: [['C'], ['C'], ['C', 'C7'], ['C7', 'F'], ['F', 'G7', 'C']],
    links: [
      'https://www.ukulele-tabs.com/uke-songs/elvis-presley/thats-alright-mama-uke-tab-66753.html',
      'https://www.youtube.com/watch?v=u4KpXlanzDA',
    ],
    kind: 'song',
  },
  {
    title: 'Down In The River To Pray',
    chords: ['G', 'C', 'D7'],
    lines: [
      ['Chorus'],
      ['G'],
      ['C', 'G'],
      ['G'],
      ['D7', 'C', 'G'],
      ['Verse'],
      ['D7', 'C', 'G'],
      ['G', 'C', 'G'],
      ['D7', 'C', 'G'],
      ['D7', 'C', 'G'],
    ],
    links: [
      'https://www.ukulele-tabs.com/uke-songs/folk-songs/down-in-the-river-to-pray-uke-tab-67392.html',
    ],
    kind: 'song',
  },
  {
    title: 'Stand By Me',
    chords: ['C', 'Am', 'F', 'G'],
    lines: [
      ['Intro'],
      ['C', 'Am', 'F', 'G', 'C'],
      ['Verse'],
      ['C', 'Am'],
      ['F', 'G', 'C'],
      ['C', 'Am'],
      ['F', 'G', 'C'],
      ['Chorus'],
      ['C'],
      ['Am'],
      ['F', 'G', 'C'],
      ['Instrumental'],
      ['C', 'Am', 'F', 'G', 'C'],
    ],
    links: [
      'https://www.ukulele-tabs.com/uke-songs/ben-e-king/stand-by-me-uke-tab-15389.html',
    ],
    kind: 'song',
  },
  {
    title: "Hey Good Lookin'",
    chords: ['C', 'D', 'F', 'G'],
    lines: [['C'], ['C'], ['D', 'G', 'C'], ['C'], ['C'], ['D', 'G', 'C']],
    links: ['https://ukutabs.com/h/hank-williams/hey-good-lookin/'],
    kind: 'song',
  },
  {
    title: 'You Are My Sunshine',
    chords: ['C', 'C7', 'G7', 'F', 'G'],
    lines: [
      ['C', 'C7'],
      ['C7', 'G7', 'C', 'F', 'C', 'C7'],
      ['C7', 'G7', 'C', 'F', 'C', 'C7'],
      ['C', 'G7', 'C'],
    ],
    links: [
      'https://www.ukulele-tabs.com/uke-songs/folk-songs/you-are-my-sunshine-uke-tab-44689.html',
    ],
    kind: 'song',
  },
  {
    title: "It's Now Or Never",
    chords: ['C', 'Dm', 'G', 'G7', 'Fm'],
    lines: [
      ['Intro'],
      ['C', 'G7', 'C'],
      ['Chorus'],
      ['C', 'Dm'],
      ['G7', 'C'],
      ['Fm', 'C'],
      ['G7', 'C'],
      ['Verse'],
      ['C', 'Dm'],
      ['G7', 'C'],
      ['C', 'Dm'],
      ['C', 'G7', 'C'],
    ],
    links: ['https://www.youtube.com/watch?v=h_XsMQZlzrQ'],
    kind: 'song',
  },
  {
    title: "Cups (When I'm Gone)",
    chords: ['C', 'F', 'Am', 'G'],
    lines: [['to do...'], ['to do...'], ['to do...'], ['to do...']],
    links: ['https://www.youtube.com/watch?v=JGI1LWfFIZQ'],
    kind: 'song',
  },

  {
    title: 'Hot Potato',
    chords: ['C', 'A', 'G#', 'G', 'Dm'],
    lines: [
      ['Chorus'],
      ['C'],
      ['C'],
      ['C'],
      ['A'],
      ['G#', 'G', 'C'],
      ['Whiggy, Whiggy'],
      ['Dm'],
      ['Dm'],
      ['C'],
    ],
    links: [
      'https://tabs.ultimate-guitar.com/tab/the-wiggles/hot-potato-ukulele-1380803',
    ],
    kind: 'song',
  },
  {
    title: 'I Saw The Light',
    chords: ['G', 'C', 'D'],
    lines: [['G'], ['C', 'G'], ['G'], ['G', 'D', 'G']],
    links: [
      'https://www.ukulele-tabs.com/uke-songs/hank-williams/i-saw-the-light-uke-tab-47708.html',
    ],
    kind: 'song',
  },
  {
    title: 'I Am A Man Of Constant Sorrow',
    chords: ['F', 'C6', 'Bes'],
    lines: [
      ['Intro'],
      ['F', 'C6', 'F'],
      ['---'],
      ['F', 'Bes'],
      ['C6', 'F'],
      ['Bes'],
      ['C6', 'F'],
      ['C6', 'F'],
    ],
    links: [
      'https://ukutabs.com/s/soggy-bottom-boys/i-am-a-man-of-constant-sorrow/',
    ],
    kind: 'song',
  },

  {
    title: 'Hallelujah',
    chords: ['Am', 'C', 'Em', 'F', 'G'],
    lines: [
      ['Verse'],
      ['C', 'Am'],
      ['C', 'Am'],
      ['F', 'G', 'C', 'G'],
      ['Pre-Chorus'],
      ['C', 'F', 'G'],
      ['Am', 'F'],
      ['G', 'Em', 'Am'],
      ['Chorus'],
      ['F', 'Am'],
      ['F', 'C', 'G', 'C', 'C'],
      ['Outro'],
      ['F', 'Am', 'F', 'C', 'G'],
      ['C'],
    ],
    links: ['https://ukutabs.com/l/leonard-cohen/hallelujah/'],
    kind: 'song',
  },
  {
    title: 'Harvest Moon',
    chords: ['F', 'C', 'Am', 'G', 'Dm', 'D', 'Bm', 'Dmaj7', 'A', 'Em'],
    lines: [['Intro'], ['C', 'Am', 'C', 'Am'], ['Enzovoorts...'], ['TO DO...']],
    links: [
      'https://tabs.ultimate-guitar.com/tab/neil-young/harvest-moon-chords-1087598',
    ],
    kind: 'song',
  },
]
